experiment:
  project: "Resnet_VLP"
  name: "Resnet_VLP_run1"
  output_dir: "/scratch2/e0724993/Resnet_VLP_run1"
  save_every: 1
  log_every: 0.1
  eval_every: 1
  log_grad_norm_every: 0.25
  resume: True
  init_weight:

model:
  tokenizer: /hpctmp/e0724993/pretrain_models/MBart_trimmed_CSL
  transformer: /hpctmp/e0724993/pretrain_models/MBart_trimmed_CSL # textCLIP only = 12 layers
  visual_encoder: /hpctmp/e0724993/pretrain_models/mytran_CSL # text decoder and Image CLIP = 3 layers
  sign_proj: True

dataset:
  name: CSL-Daily
  lang: zh_CN
  train: /hpctmp/e0724993/CSL-Daily/sentence_label/processed/labels_train.pkl
  dev: /hpctmp/e0724993/CSL-Daily/sentence_label/processed/labels_dev.pkl
  test: /hpctmp/e0724993/CSL-Daily/sentence_label/processed/labels_test.pkl
  img_path: /hpctmp/e0724993/CSL-Daily/sentence/frames_512x512/ # + <train/dev/test> + <video_name>
  max_length: 300
  params:
    num_workers: 4
  preprocessing:
    crop_size: 224
    resize_shorter_edge: 256
    random_crop: True
    random_flip: True
    person_size: 410

optimizer:
  name: sgd
  params:
    learning_rate: 1e-3
    beta1: 0.9
    beta2: 0.99
    weight_decay: 1e-4

lr_scheduler:
  scheduler: cosine
  params:
    learning_rate: ${optimizer.params.learning_rate}
    warmup_steps: 4000
    end_lr: 1e-4

training:
  gradient_accumulation_steps: 8 
  per_gpu_batch_size: 2
  mixed_precision: "fp16"
  enable_tf32: True
  enable_wandb: False
  use_ema: False
  seed: 42
  num_translated_images: 4
  max_grad_norm: 1.0
  num_epochs: 32
  scale_embedding: False
