experiment:
  project: "Resnet_VLP"
  name: "Resnet_VLP_run1"
  output_dir: "../Resnet_VLP_run1"
  save_every: 1
  log_every: 0.1
  translate_every: 0.25
  eval_every: 1
  log_grad_norm_every: 0.1
  resume: True
  init_weight:

model:
  tokenizer: facebook/mbart-large-50-many-to-many-mmt # ./pretrain_models/mbart_model
  transformer: facebook/mbart-large-50-many-to-many-mmt # textCLIP only = 12 layers
  visual_encoder: ./pretrain_models/mytran # text decoder and Image CLIP = 3 layers
  sign_proj: True

dataset:
  name: CSL-Daily
  lang: zh_CN
  train: ../../CSL-Daily/sentence_label/processed/labels_train.pkl
  dev: ../../CSL-Daily/sentence_label/processed/labels_dev.pkl
  test: ../../CSL-Daily/sentence_label/processed/labels_test.pkl
  img_path: ../../CSL-Daily/sentence/frames_512x512/ # + <train/dev/test> + <video_name>
  max_length: 300
  params:
    num_workers: 4
  preprocessing:
    crop_size: 224
    resize_shorter_edge: 256
    random_crop: True
    random_flip: True
    person_size: 410

optimizer:
  name: adamw
  params:
    learning_rate: 1e-4
    beta1: 0.9
    beta2: 0.99
    weight_decay: 1e-4

lr_scheduler:
  scheduler: cosine
  params:
    learning_rate: ${optimizer.params.learning_rate}
    warmup_steps: 4000
    end_lr: 1e-5

training:
  gradient_accumulation_steps: 1
  per_gpu_batch_size: 4
  mixed_precision: "no"
  enable_tf32: True
  enable_wandb: False
  use_ema: False
  seed: 42
  num_translated_images: 4
  max_grad_norm: 1.0
  num_epochs: 32
  scale_embedding: False
