experiment:
  project: "titok_l_32_stage1"
  name: "titok_l_32_stage1_run1"
  output_dir: "titok_l_32_stage1_run1"
  generate_every: 0.25
  save_every: 0.25
  log_every: 1
  eval_every: 1
  log_grad_norm_every: 0.1
  resume: True
  init_weight: "tokenizer_titok_l32.bin"

model:
  vq_model:
    codebook_size: 4096
    token_size: 12
    use_l2_norm: True
    commitment_cost: 0.25
    # vit arch
    vit_enc_model_size: "large"
    vit_dec_model_size: "large"
    vit_enc_patch_size: 16
    vit_dec_patch_size: 16
    num_latent_tokens: 32
    finetune_decoder: False
    pretrained_tokenizer_weight: "maskgit-vqgan-imagenet-f16-256.bin"

losses:
  quantizer_weight: 1.0

dataset:
  params:
    img_path: ../../CSL-Daily/sentence/frames_512x512/ # might need to resize
    num_workers: 10
  preprocessing:
    resize_shorter_edge: 256
    crop_size: 256
    random_crop: True
    random_flip: True
    person_size : (410,410)

optimizer:
  name: adamw
  params:
    learning_rate: 1e-4
    beta1: 0.9
    beta2: 0.99
    weight_decay: 1e-4

lr_scheduler:
  scheduler: "cosine"
  params:
    learning_rate: ${optimizer.params.learning_rate}
    warmup_steps: 10_000
    end_lr: 1e-5

training:
  gradient_accumulation_steps: 1
  per_gpu_batch_size: 32
  mixed_precision: "fp16"
  enable_tf32: True
  enable_wandb: False
  use_ema: True
  seed: 42
  num_generated_images: 4
  max_grad_norm: 1.0
  num_epochs: 10
  frame_every: 5
