name: GFSLT-VLP CSL-Daily
data:
  train: ../../CSL-Daily/sentence_label/processed/labels_train.pkl
  dev: ../../CSL-Daily/sentence_label/processed/labels_dev.pkl
  test: ../../CSL-Daily/sentence_label/processed/labels_test.pkl
  img_path: ../../CSL-Daily/sentence/frames_512x512 # + <train/dev/test> + <video_name>
  max_length: 300
training:
  wandb: disabled # online or disabled
  scale_embedding: False
model:
  transformer: ./pretrain_models/CSL/MBart_trimmed
  visual_encoder: ./pretrain_models/CSL/mytran
  sign_proj: True
