experiment:
  project: SpaEMo_P14
  name: SpaEMo_P14_run1
  output_dir: ../SpaEMo_P14_run1
  save_every: 1
  log_every: 0.1
  eval_every: 1
  translate_every: 0.25
  log_grad_norm_every: 0.1
  resume: true
  init_weight: null
  logging_dir: ../SpaEMo_P14_run1\logs
model:
  tokenizer: text/gemma_instruct_2b
  emotion_model: trpakov/vit-face-expression
  spatio_model: openai/clip-vit-large-patch14
  motion_model: MCG-NJU/videomae-large-finetuned-kinetics
  llm: text/gemma_instruct_2b
  transformer_type: causal
  emo_hiddim: 768
  spatio_hiddim: 768
  motion_hiddim: 1024
dataset:
  name: PHOENIX2014T
  prompt: 'Translate the following sentence into spoken German:'
  lang: de_DE
  train: ../../PHOENIX-2014-T-release-v3/PHOENIX-2014-T/annotations/processed/labels_train.pkl
  dev: ../../PHOENIX-2014-T-release-v3/PHOENIX-2014-T/annotations/processed/labels_dev.pkl
  test: ../../PHOENIX-2014-T-release-v3/PHOENIX-2014-T/annotations/processed/labels_test.pkl
  img_path: ../../PHOENIX-2014-T-release-v3/PHOENIX-2014-T/features/fullFrame-210x260px
  max_length: 300
  params:
    num_workers: 4
optimizer:
  name: adamw
  params:
    learning_rate: 0.0001
    beta1: 0.9
    beta2: 0.98
    weight_decay: 0.01
lr_scheduler:
  scheduler: cosine
  params:
    learning_rate: ${optimizer.params.learning_rate}
    warmup_steps: 4000
    end_lr: 5.0e-05
training:
  gradient_accumulation_steps: 8
  per_gpu_batch_size: 2
  mixed_precision: fp16
  enable_tf32: true
  enable_wandb: false
  use_ema: false
  seed: 42
  num_translated_images: 4
  max_grad_norm: 1.0
  num_epochs: 32
  scale_embedding: false
config: configs/SpaEMo_P14_config.yaml
--experiment:
  project: SpaEMo_P14
  name: SpaEMo_P14_run1
  output_dir: SpaEMo_P14_run1
